# Generated by Django 6.0.6 on 2026-06-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='proof_image',
            field=models.ImageField(blank=True, upload_to='proofs/'),
        ),
        migrations.AddField(
            model_name='task',
            name='proof_note',
            field=models.TextField(blank=True),
        ),
    ]
