# Generated by Django 5.2.15 on 2026-07-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_status_proof_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('done', 'Done'), ('closed', 'Closed')], default='open', max_length=12),
        ),
    ]
